import {api,configured} from './api.js';
import {standardCategories} from './categories.js';
import {today,money,cents,inputMoney,addMonths,split,billMonth,balance,totals,cardBill,isSpending,validate,monthlyForecast} from './finance.js';
const $=s=>document.querySelector(s), root=$('#root'), modal=$('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
const types={income:'Receita',expense:'Despesa',transfer:'Transferência',card:'Compra no cartão',card_payment:'Pagamento de fatura'};
const pages=[['dashboard','◫','Visão geral'],['entries','⇅','Lançamentos'],['accounts','▤','Contas'],['cards','▱','Cartões'],['planning','◎','Orçamentos e metas'],['projects','◈','Projetos'],['reports','▥','Relatórios'],['settings','⚙','Configurações']];
let rows=[],member='',page='dashboard',month=today().slice(0,7),filter='',typeFilter='',statusFilter='',accountFilter='',editor=null,busy=false,loading=false,hidden=false,refreshTimer;
const list=kind=>rows.filter(r=>r.kind===kind).map(r=>({...r.data,id:r.id,version:r.version}));
const entries=()=>list('entry');
const find=(kind,id)=>list(kind).find(r=>r.id===id);
const title=kind=>({account:'conta',entry:'lançamento',card:'cartão',budget:'orçamento',goal:'meta',project:'projeto'}[kind]);
const dateText=d=>d?`${d.slice(8,10)}/${d.slice(5,7)}/${d.slice(2,4)}`:'—';
const periodText=m=>`${m.slice(5,7)}/${m.slice(2,4)}`;
const valueClass=n=>n<0?'negative':n>0?'positive':'neutral';
function monthOptions(selected){return Array.from({length:121},(_,i)=>addMonths(selected+'-01',i-60).slice(0,7)).map(m=>`<option value="${m}" ${m===selected?'selected':''}>${periodText(m)}</option>`).join('');}
const amount=n=>`<span class="num">${money(n)}</span>`;
const sum=(es,fn=()=>true)=>es.filter(fn).reduce((s,e)=>s+e.amount,0);
const btn=(action,label,cls='',attrs='')=>`<button type="button" data-action="${action}" class="${cls}" ${attrs}>${label}</button>`;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4500);}
function empty(text,detail=''){return `<div class="empty"><span class="empty-symbol">◇</span><b>${esc(text)}</b><p>${esc(detail)}</p></div>`;}
function metric(label,value,note,cls='',flow=''){return `<div class="card ${cls}"><div class="label">${label}</div><div class="value ${flow==='out'&&value>0?'negative':valueClass(value)}">${money(value)}</div><small>${note}</small></div>`;}
function bar(name,value,total,label){const pct=total?Math.max(0,value/total*100):0;return `<div class="barrow"><div class="barlabels"><span>${esc(name)}</span><b>${label||money(value)}</b></div><div class="bartrack"><div class="barfill ${pct>100?'over':''}" style="width:${Math.min(100,pct)}%"></div></div></div>`;}
function heading(name,desc,controls=''){return `<div class="pagehead"><div><h1>${name}</h1><p>${desc}</p></div>${controls}</div>`;}
const monthInput=()=>`<div class="period-control">${btn('previous-month','‹','period-step','aria-label="Mês anterior"')}<select class="period" id="period" aria-label="Mês de referência">${monthOptions(month)}</select>${btn('next-month','›','period-step','aria-label="Próximo mês"')}</div>`;
function login(message=''){
 clearInterval(refreshTimer);rows=[];member='';modal.close();root.innerHTML=`<div class="login"><section class="login-story"><div class="brand"><span class="mark">≋</span>Meu Financeiro</div><h1>Mais clareza.<br><span>Mais planos<br>em família.</span></h1><p>Um lugar para cuidar das contas de hoje e das conquistas de amanhã.</p><div class="story-stats"><div><b>Uma visão compartilhada</b><small>O mesmo planejamento, juntos.</small></div></div></section><main class="login-panel" id="main"><form id="login-form"><div class="eyebrow muted">SEU ESPAÇO FINANCEIRO</div><h2 style="margin-top:18px">Que bom ter você aqui.</h2><p class="muted">Entre para acompanhar as finanças da família.</p>${!configured()?'<div class="notice"><b>Falta conectar seu banco de dados.</b><br>Use o guia que acompanha o aplicativo para configurar o arquivo config.js e cadastrar os dois usuários.</div>':''}<label for="email">E-mail</label><input id="email" name="email" type="email" autocomplete="username" required placeholder="voce@exemplo.com"><label for="password">Senha</label><input id="password" name="password" type="password" autocomplete="current-password" required minlength="8"><p class="error" id="login-error" role="alert">${esc(message)}</p><button class="primary" ${configured()?'':'disabled'}>Entrar na minha conta</button><p class="muted" style="font-size:.8rem;margin-top:24px;line-height:1.6">Acesso restrito aos usuários autorizados.<br>Precisa redefinir a senha? O responsável pelo projeto pode enviar a recuperação pelo painel do Supabase.</p></form></main></div>`;
 $('#login-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('#login-error').textContent='';try{await api.login($('#email').value.trim(),$('#password').value);await start();}catch(err){$('#login-error').textContent='Não foi possível entrar. Confira e-mail, senha e conexão.';}finally{b.disabled=false;}};
}
async function load(){if(loading)return;loading=true;try{const result=await api.records();rows=result;}finally{loading=false;}}
async function start(){try{member=(await api.member())?.name;if(!member){await api.logout();login('Seu usuário ainda não foi autorizado. Solicite a liberação ao responsável.');return;}await load();render();clearInterval(refreshTimer);refreshTimer=setInterval(async()=>{if(document.hidden||document.querySelector('dialog[open]')||busy||loading)return;try{await load();render();}catch{showSyncError();}},30000);}catch(e){login('Não foi possível carregar o espaço. Verifique a conexão e a configuração de acesso.');}}
function showSyncError(){if(!$('#sync-error'))$('.workspace')?.insertAdjacentHTML('afterbegin','<div class="sync-error" id="sync-error">Não foi possível atualizar. Os valores exibidos podem estar desatualizados. Use Atualizar.</div>');}
function mobileNavigation(){
 const tab=(id,icon,label)=>btn('page',`<span aria-hidden="true">${icon}</span><small>${label}</small>`,page===id?'active':'',`data-page="${id}" ${page===id?'aria-current="page"':''}`);
 return `<nav class="bottom-nav" aria-label="Navegação do aplicativo">${tab('dashboard','◫','Início')}${tab('entries','⇅','Extrato')}${btn('new','<span aria-hidden="true">+</span><small>Lançar</small>','nav-add','data-kind="entry" aria-label="Novo lançamento"')}${tab('cards','▱','Cartões')}${btn('more','<span aria-hidden="true">☰</span><small>Mais</small>',['accounts','planning','projects','reports','settings'].includes(page)?'active':'','aria-label="Mais opções"')}</nav><dialog id="nav-dialog" class="nav-dialog" aria-labelledby="nav-title"><div class="dialog-head"><h2 id="nav-title">Seu financeiro</h2>${btn('close-more','×','','aria-label="Fechar menu"')}</div><nav class="menu-grid" aria-label="Outras opções">${pages.filter(([id])=>!['dashboard','entries','cards'].includes(id)).map(([id,icon,label])=>tab(id,icon,label)).join('')}</nav>${btn('logout','Sair da conta','menu-logout')}</dialog>`;
}
function render(){root.innerHTML=`<div class="app ${hidden?'privacy':''}"><aside class="sidebar"><div class="brand"><span class="mark">≋</span>Meu Financeiro</div><div class="eyebrow">ESPAÇO DA FAMÍLIA</div><nav class="nav" aria-label="Principal">${pages.map(([id,icon,text])=>btn('page',`<span>${icon}</span>${text}`,page===id?'active':'',`data-page="${id}" ${page===id?'aria-current="page"':''}`)).join('')}</nav><div class="sidebar-foot"><strong>Planejar é cuidar.</strong>Um passo de cada vez.<br>Dados compartilhados com a família.</div></aside><div class="workspace"><header class="topbar"><div class="topbar-left">Espaço compartilhado · <strong>${esc(member)}</strong></div><div class="top-actions">${btn('refresh','Atualizar')}${btn('privacy',hidden?'Mostrar valores':'Ocultar valores','',`aria-pressed="${hidden}"`)}${btn('logout','Sair')}<span class="avatar">${esc(member[0]?.toUpperCase())}</span></div></header><main class="content" id="main">${screens[page]()}</main>${mobileNavigation()}</div></div>`;}
function filtered(){return entries().filter(e=>e.date.startsWith(month)&&(!filter||(e.description+' '+e.category).toLowerCase().includes(filter.toLowerCase()))&&(!typeFilter||e.type===typeFilter)&&(!statusFilter||e.status===statusFilter)&&(!accountFilter||e.account===accountFilter||e.to===accountFilter)).sort((a,b)=>b.date.localeCompare(a.date)||a.description.localeCompare(b.description));}
function entryTable(es,compact=false){if(!es.length)return empty('Nenhum lançamento por aqui.','Adicione uma receita ou despesa para começar.');return `<div class="tablewrap entries-table"><table><thead><tr><th>Descrição</th><th>Data</th><th>Situação</th><th class="num">Valor</th>${compact?'':'<th>Ações</th>'}</tr></thead><tbody>${es.map(e=>`<tr><td class="tx-description"><strong>${esc(e.description)}</strong><small>${esc(e.category||types[e.type])} · ${esc(find(e.type==='card'?'card':'account',e.type==='card'?e.card:e.account)?.name||'—')}${e.installment?' · '+esc(e.installment):''}</small></td><td class="tx-date">${dateText(e.date)}</td><td class="tx-status"><span class="badge ${e.status==='pending'?(e.date<today()?'late':'pending'):''}">${e.status==='pending'?(e.date<today()?'Em atraso':'Pendente'):e.type==='card'?'Na fatura':'Confirmado'}</span></td><td class="num tx-value ${e.type==='income'?'positive':(isSpending(e)||e.type==='card_payment')?'negative':''}">${e.type==='income'?'+ ':(isSpending(e)||e.type==='card_payment')?'− ':''}${money(e.amount)}</td>${compact?'':`<td class="actions tx-actions">${e.status==='pending'?btn('settle','Baixar','',`data-id="${e.id}"`):''}${btn('edit','Editar','',`data-kind="entry" data-id="${e.id}"`)}${btn('delete','Excluir','danger',`data-kind="entry" data-id="${e.id}"`)}</td>`}</tr>`).join('')}</tbody></table></div>`;}
function forecastTable(items){
 if(!items.length)return empty('Nenhum valor pendente neste mês.','Receitas, despesas e faturas previstas aparecerão aqui.');
 return `<div class="tablewrap entries-table"><table><thead><tr><th>Descrição</th><th>Vencimento</th><th>Situação</th><th class="num">Valor</th><th>Ações</th></tr></thead><tbody>${items.map(e=>`<tr><td class="tx-description"><strong>${esc(e.description)}</strong><small>${e.forecastKind==='invoice'?`Fechamento ${periodText(e.bill)} · saldo restante`:esc(e.category||types[e.type])}${e.installment?' · '+esc(e.installment):''}</small></td><td class="tx-date">${dateText(e.date)}</td><td class="tx-status"><span class="badge ${e.date<today()?'late':'pending'}">${e.date<today()?'Em atraso':e.type==='income'?'A receber':'A pagar'}</span></td><td class="num tx-value ${e.type==='income'?'positive':'negative'}">${e.type==='income'?'+ ':'− '}${money(e.amount)}</td><td class="actions tx-actions">${e.forecastKind==='invoice'?btn('pay-card','Pagar fatura','',`data-id="${e.card}" data-bill="${e.bill}"`):btn('settle',e.type==='income'?'Receber':'Pagar','',`data-id="${e.id}"`)+btn('edit','Editar','',`data-kind="entry" data-id="${e.id}"`)}</td></tr>`).join('')}</tbody></table></div>`;
}
function dashboard(){
 const es=entries(),t=totals(es,month),f=monthlyForecast(list('account'),list('card'),es,month);
 const cats={};es.filter(e=>e.date.startsWith(month)&&isSpending(e)&&(e.status==='paid'||e.type==='card')).forEach(e=>cats[e.category||'Outros']=(cats[e.category||'Outros']||0)+e.amount);
 const recent=es.filter(e=>e.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
 const message=f.historical?'Este mês já terminou. O saldo de fechamento considera apenas movimentações confirmadas.':f.expectedEnd<0?`Previsão de faltar ${money(-f.expectedEnd)} no fim de ${periodText(month)}.`:f.expectedEnd>0?`Previsão de sobrar ${money(f.expectedEnd)} no fim de ${periodText(month)}.`:`A previsão é fechar ${periodText(month)} com saldo zerado.`;
 return heading('Visão geral','Seu saldo e os compromissos do mês.',monthInput())+
 (!list('account').length?`<div class="onboarding"><div><h2>Vamos organizar o primeiro passo?</h2><p>Cadastre uma conta com o saldo anterior aos lançamentos que você vai registrar.</p></div>${btn('new','+ Cadastrar conta','primary','data-kind="account"')}</div>`:'')+
 `<div class="cards forecast-cards">${metric(f.historical?'Saldo registrado no fim':'Saldo previsto no fim',f.expectedEnd,`Fechamento de ${periodText(month)}${f.historical?' · confirmado':' · estimativa'}`,'featured')}${metric('Disponível agora',f.available,'Saldo confirmado nas contas · hoje')}${metric(`A receber em ${periodText(month)}`,f.receivable,'Receitas pendentes deste mês')}${metric(`A pagar em ${periodText(month)}`,f.payable,'Despesas pendentes + saldo das faturas','','out')}</div>
 <section class="forecast-status ${f.historical?'':valueClass(f.expectedEnd)}" aria-label="Previsão do mês"><strong>${message}</strong><p>${f.historical?'As pendências listadas abaixo ainda estão abertas hoje. Elas não alteram o saldo histórico confirmado.':'Considera o saldo de hoje e tudo que ainda falta receber e pagar até o fim do mês, incluindo pendências anteriores. A previsão depende da confirmação dos recebimentos e não garante saldo suficiente em cada vencimento.'}</p>
 ${!f.historical?`<details class="forecast-formula"><summary>Como a previsão foi calculada</summary><div class="forecast-equation"><span>Saldo de hoje <b class="${valueClass(f.available)}">${money(f.available)}</b></span><span>+ A receber no mês <b class="positive">${money(f.receivable)}</b></span><span>− A pagar no mês <b class="negative">${money(f.payable)}</b></span><span>+ A receber de meses anteriores <b class="positive">${money(f.priorReceivable)}</b></span><span>− A pagar de meses anteriores <b class="negative">${money(f.priorPayable)}</b></span><span class="forecast-total">= Saldo previsto <b class="${valueClass(f.expectedEnd)}">${money(f.expectedEnd)}</b></span></div><p>As faturas entram pelo mês de vencimento, apenas pelo valor ainda não pago. Transferências entre suas contas não alteram esta previsão.</p></details>`:''}</section>
 <section class="panel monthly-cash"><div class="panel-head"><h2>Movimentação de ${periodText(month)}</h2></div><div class="monthly-cash-grid"><div><span>${f.historical?'Recebido no mês':'Receitas recebidas + previstas'}</span><b class="${valueClass(f.historical?f.received:f.totalIncome)}">${money(f.historical?f.received:f.totalIncome)}</b><small>Recebido: ${money(f.received)}</small></div><div><span>${f.historical?'Pago no mês':'Saídas pagas + previstas'}</span><b class="negative">${money(f.historical?f.spent:f.totalOutgoings)}</b><small>Pago: ${money(f.spent)}</small></div><div><span>${f.historical?'Resultado realizado':'Resultado previsto do mês'}</span><b class="${valueClass(f.historical?f.received-f.spent:f.totalIncome-f.totalOutgoings)}">${money(f.historical?f.received-f.spent:f.totalIncome-f.totalOutgoings)}</b><small>Movimento do mês, sem somar o saldo anterior</small></div></div></section>
 <section class="panel forecast-items"><div class="panel-head"><h2>${f.historical?'Pendências':'Previstos'} de ${periodText(month)} <span class="count-badge">${f.selected.length}</span></h2>${btn('new','+ Adicionar','textbtn','data-kind="entry"')}</div><p class="muted forecast-caption">${f.historical?'Valores deste mês que ainda não foram liquidados.':'Todos os recebimentos, despesas e faturas ainda em aberto com vencimento neste mês.'}</p>${forecastTable(f.selected)}</section>
 ${f.prior.length?`<details class="panel previous-pending"><summary>Pendências anteriores a ${periodText(month)} <span class="count-badge">${f.prior.length}</span></summary><p class="muted forecast-caption">${f.historical?'Ainda abertas hoje.':'Incluídas no saldo previsto, para não esconder compromissos de meses anteriores.'} A receber: ${money(f.priorReceivable)} · a pagar: ${money(f.priorPayable)}.</p>${forecastTable(f.prior)}</details>`:''}
 <div class="grid2"><section class="panel"><div class="panel-head"><h2>Receitas e gastos por mês</h2><div class="legend"><span><i></i>Receitas</span><span><i class="out"></i>Gastos</span></div></div>${chart(es)}</section><section class="panel"><div class="panel-head"><h2>Gastos por categoria</h2></div>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,v])=>bar(name,v,t.expense)).join('')||empty('Tudo pronto para começar.','Suas categorias aparecerão aqui.')}</section></div><section class="panel"><div class="panel-head"><h2>Últimos lançamentos do mês</h2>${btn('page','Ver todos','textbtn','data-page="entries"')}</div>${entryTable(recent,true)}</section>`;
}

function chart(es){const months=Array.from({length:6},(_,i)=>addMonths(month+'-01',i-5).slice(0,7));const ts=months.map(m=>totals(es,m)),max=Math.max(1,...ts.flatMap(t=>[t.income,t.expense]));return `<div class="chart">${months.map((m,i)=>`<div class="chart-col"><div class="chart-bars"><div class="chart-bar" style="height:${ts[i].income/max*150}px" title="Recebido: ${money(ts[i].income)}"></div><div class="chart-bar out" style="height:${ts[i].expense/max*150}px" title="Gastos: ${money(ts[i].expense)}"></div></div><small>${periodText(m)}</small></div>`).join('')}</div>`;}
function entryScreen(){return heading('Lançamentos','Receitas, despesas e movimentações em um só lugar.',btn('new','+ Novo lançamento','primary','data-kind="entry"'))+`<div class="toolbar">${monthInput()}<input id="search" type="search" placeholder="Buscar descrição ou categoria" aria-label="Buscar lançamentos" value="${esc(filter)}"><select id="type-filter" aria-label="Tipo"><option value="">Todos os tipos</option>${Object.entries(types).map(([v,n])=>`<option value="${v}" ${typeFilter===v?'selected':''}>${n}</option>`).join('')}</select><select id="status-filter" aria-label="Situação"><option value="">Todas as situações</option><option value="paid" ${statusFilter==='paid'?'selected':''}>Confirmados</option><option value="pending" ${statusFilter==='pending'?'selected':''}>Pendentes</option></select><select id="account-filter" aria-label="Conta"><option value="">Todas as contas</option>${list('account').map(a=>`<option value="${a.id}" ${a.id===accountFilter?'selected':''}>${esc(a.name)}</option>`).join('')}</select>${btn('csv','Exportar CSV')}</div><section class="panel" id="entries-table">${entryTable(filtered())}</section>`;}
function accountScreen(){const es=entries();return heading('Suas contas','Saldos calculados a partir das movimentações confirmadas.',btn('new','+ Cadastrar conta','primary','data-kind="account"'))+`<div class="grid3">${list('account').map(a=>`<section class="panel account-tile"><div class="eyebrow muted">${esc(a.bank||'CONTA DA FAMÍLIA')}</div><h2 style="margin-top:12px">${esc(a.name)}</h2><div class="amount ${valueClass(balance(a,es))}">${money(balance(a,es))}</div><footer><small>Saldo atual · BRL</small>${btn('edit','Editar','textbtn',`data-kind="account" data-id="${a.id}"`)}</footer>${btn('delete','Excluir conta','textbtn danger',`data-kind="account" data-id="${a.id}"`)}</section>`).join('')}</div>${!list('account').length?empty('Cadastre sua primeira conta.','Conta corrente, poupança ou carteira em dinheiro.'):'<p class="muted" style="margin-top:25px;font-size:.85rem">Transferências entre contas não entram como receita ou despesa. O saldo inicial é o ponto de partida anterior ao seu histórico.</p>'}`;}
function cardScreen(){const es=entries();return heading('Cartões de crédito','Selecione o mês de fechamento da fatura.',monthInput()+btn('new','+ Novo cartão','primary','data-kind="card"'))+`<div class="grid3">${list('card').map(c=>{const bill=cardBill(es,c.id,month),used=es.filter(e=>e.card===c.id).reduce((s,e)=>s+(e.type==='card'?e.amount:-e.amount),0);return `<section class="panel credit"><div class="eyebrow">CARTÃO DE CRÉDITO</div><h2 style="margin-top:15px">${esc(c.name)}</h2><div class="amount" style="font-size:1.9rem;font-weight:700">${money(bill)}</div><p class="muted">Saldo da fatura · ${periodText(month)}</p><small>Fecha dia ${c.closing} · vence dia ${c.due}${c.due<=c.closing?' do mês seguinte':''}</small><hr style="border:0;border-top:1px solid #ffffff22;margin:22px 0"><div class="barlabels"><span>Limite disponível</span><b class="${valueClass(c.limit-used)}">${money(c.limit-used)}</b></div><small>Limite total ${money(c.limit)} · inclui parcelas futuras</small><div class="setting-actions" style="margin-top:22px">${btn('purchase','+ Compra','',`data-id="${c.id}"`)}${btn('pay-card','Pagar fatura','',`data-id="${c.id}" ${bill<=0?'disabled':''}`)}</div><div style="margin-top:15px">${btn('edit','Editar cartão','textbtn',`data-kind="card" data-id="${c.id}"`)} · ${btn('delete','Excluir','textbtn',`data-kind="card" data-id="${c.id}"`)}</div></section>`;}).join('')}</div><h2 class="section-title">Compras e pagamentos desta fatura</h2><section class="panel">${entryTable(es.filter(e=>e.bill===month).sort((a,b)=>a.date.localeCompare(b.date)))}</section>`;}
function planning(){const es=entries().filter(e=>e.date.startsWith(month)&&isSpending(e));return heading('Planejar para realizar','Limites mensais e objetivos compartilhados.',monthInput())+`<div class="panel-head"><h2>Orçamentos por categoria</h2>${btn('new','+ Orçamento','primary','data-kind="budget"')}</div><div class="grid3">${list('budget').map(b=>{const actual=sum(es,e=>e.category===b.category&&(e.status==='paid'||e.type==='card')),planned=sum(es,e=>e.category===b.category&&e.status==='pending');return `<section class="panel"><h2>${esc(b.name)}</h2>${bar(b.category,actual,b.target)}<small>Limite ${money(b.target)} · ${Math.round(actual/b.target*100)}% usado</small><p class="muted" style="margin-top:15px;font-size:.84rem">Pendente: ${money(planned)}<br>Disponível após pendências: <b class="${valueClass(b.target-actual-planned)}">${money(b.target-actual-planned)}</b></p>${btn('edit','Editar','textbtn',`data-kind="budget" data-id="${b.id}"`)} · ${btn('delete','Excluir','textbtn danger',`data-kind="budget" data-id="${b.id}"`)}</section>`;}).join('')}</div>${!list('budget').length?empty('Quanto você quer gastar por mês?','Defina um limite para cada categoria.') :''}<div class="panel-head section-title"><h2>Metas da família</h2>${btn('new','+ Nova meta','primary','data-kind="goal"')}</div><div class="grid3">${list('goal').map(g=>`<section class="panel"><h2>${esc(g.name)}</h2>${bar('Valor reservado',g.saved,g.target)}<small>Objetivo: ${money(g.target)}${g.deadline?' · até '+dateText(g.deadline):''}</small><p class="positive" style="margin-top:18px">${g.saved>=g.target?'Meta alcançada!':'Faltam '+money(g.target-g.saved)}</p>${btn('edit','Atualizar reserva','textbtn',`data-kind="goal" data-id="${g.id}"`)} · ${btn('delete','Excluir','textbtn danger',`data-kind="goal" data-id="${g.id}"`)}</section>`).join('')}</div><p class="muted" style="font-size:.84rem;margin-top:25px">As metas acompanham valores que você informa como reservados. Não movimentam contas e não são somadas novamente ao saldo.</p>`;}
function projects(){const es=entries().filter(e=>e.date.startsWith(month));return heading('Projetos e receitas extras','Acompanhe sites, comissões e custos em reais.',monthInput()+btn('new','+ Novo projeto','primary','data-kind="project"'))+`<div class="grid3">${list('project').map(p=>{const mine=es.filter(e=>e.project===p.id),received=sum(mine,e=>e.type==='income'&&e.status==='paid'),cost=sum(mine,e=>isSpending(e)&&(e.status==='paid'||e.type==='card')),pending=sum(mine,e=>e.type==='income'&&e.status==='pending');return `<section class="panel"><h2>${esc(p.name)}</h2><p class="muted">${esc(p.description||'Receitas e despesas do projeto')}</p><div class="barlabels"><span>Recebido</span><b class="positive">${money(received)}</b></div><div class="barlabels"><span>Custos</span><b class="${cost>0?'negative':'neutral'}">${money(cost)}</b></div><div class="barlabels"><span>Resultado</span><b class="${valueClass(received-cost)}">${money(received-cost)}</b></div><small>A receber: ${money(pending)}</small><div style="margin-top:20px">${btn('edit','Editar','textbtn',`data-kind="project" data-id="${p.id}"`)} · ${btn('delete','Excluir','textbtn danger',`data-kind="project" data-id="${p.id}"`)}</div></section>`;}).join('')}</div>${!list('project').length?empty('Cada projeto com suas próprias contas.','Cadastre um projeto e selecione-o nos lançamentos.'):''}`;}
function reports(){const es=entries(),selected=es.filter(e=>e.date.startsWith(month)),cashIn=sum(selected,e=>e.status==='paid'&&e.type==='income'),cashOut=sum(selected,e=>e.status==='paid'&&['expense','card_payment'].includes(e.type)),cats={};selected.filter(e=>isSpending(e)&&(e.status==='paid'||e.type==='card')).forEach(e=>cats[e.category||'Outros']=(cats[e.category||'Outros']||0)+e.amount);return heading('Relatórios','Duas visões: dinheiro movimentado e gastos realizados.',monthInput()+btn('print','Imprimir / PDF'))+`<div class="cards">${metric('Entradas em caixa',cashIn,'Receitas recebidas no período')}${metric('Saídas de caixa',cashOut,'Despesas pagas + pagamentos de fatura','','out')}${metric('Variação de caixa',cashIn-cashOut,'Transferências internas não incluídas')}${metric('Gastos do período',sum(selected,e=>isSpending(e)&&(e.status==='paid'||e.type==='card')),'Compras e parcelas, sem pagar fatura duas vezes','','out')}</div><div class="grid2"><section class="panel"><h2>Gastos por categoria</h2>${Object.entries(cats).map(([k,v])=>bar(k,v,Object.values(cats).reduce((a,b)=>a+b,0))).join('')||empty('Ainda não há gastos neste mês.')}</section><section class="panel"><h2>Previsão dos próximos 12 meses</h2><p class="muted" style="font-size:.85rem;line-height:1.5">Inclui lançamentos pendentes e saldo das faturas já registradas. Não prevê novas compras ou receitas ainda não cadastradas.</p><div class="tablewrap"><table><thead><tr><th>Mês</th><th class="num">A receber</th><th class="num">A pagar¹</th></tr></thead><tbody>${Array.from({length:12},(_,i)=>addMonths(today().slice(0,7)+'-01',i).slice(0,7)).map(m=>{const outgoing=sum(es,e=>e.status==='pending'&&e.type==='expense'&&e.date.startsWith(m))+list('card').reduce((s,c)=>s+Math.max(0,cardBill(es,c.id,c.due<=c.closing?addMonths(m+'-01',-1).slice(0,7):m)),0);return `<tr><td>${periodText(m)}</td><td class="num">${money(sum(es,e=>e.status==='pending'&&e.type==='income'&&e.date.startsWith(m)))}</td><td class="num">${money(outgoing)}</td></tr>`;}).join('')}</tbody></table></div><small>¹ Faturas pelo mês de vencimento. Pendências vencidas de meses anteriores não estão nesta projeção.</small></section></div>`;}
function settings(){return heading('Configurações','Sua conta, aparência e cópias dos dados.')+`<section class="panel"><div class="setting-row"><div><h3>Conta conectada</h3><p>${esc(api.user?.email)} · ${esc(member)}</p></div>${btn('password','Alterar senha')}</div><div class="setting-row"><div><h3>Aparência</h3><p>Escolha a visualização mais confortável para este dispositivo.</p></div>${btn('theme',document.body.classList.contains('dark')?'Usar tema claro':'Usar tema escuro')}</div><div class="setting-row"><div><h3>Backup completo</h3><p>Baixe contas, cartões, lançamentos, metas, orçamentos e projetos em JSON. Guarde em local privado.</p></div><div class="setting-actions">${btn('backup','Baixar backup')}${btn('restore','Restaurar backup')}</div></div><div class="setting-row"><div><h3>Planilhas de lançamentos</h3><p>Importe CSV no formato do aplicativo. A importação mostra uma prévia e ignora IDs já existentes.</p></div><div class="setting-actions">${btn('csv-all','Exportar tudo')}${btn('import','Importar CSV')}</div></div><div class="setting-row"><div><h3>Acesso da família</h3><p>Os dois usuários têm permissão para ver e editar os mesmos dados. Novos acessos são liberados no painel do Supabase, conforme o guia de instalação.</p></div></div><div class="notice"><b>Sobre esta versão</b><br>Controle manual em reais, sem conexão bancária automática. Comprovantes, OFX, múltiplas moedas e investimentos não estão incluídos. O backup não contém senhas, usuários ou histórico de auditoria.</div></section>`;}
const screens={dashboard,entries:entryScreen,accounts:accountScreen,cards:cardScreen,planning,projects,reports,settings};
function field(name,label,value='',type='text',hint='',full=false,extra=''){if(type==='month')return `<div class="field ${full?'full':''}" data-field="${name}"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${monthOptions(value||month)}</select>${hint?`<small>${hint}</small>`:''}</div>`;return `<div class="field ${full?'full':''}" data-field="${name}"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}>${hint?`<small>${hint}</small>`:''}</div>`;}
function select(name,label,options,value='',full=false){return `<div class="field ${full?'full':''}" data-field="${name}"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(text)}</option>`).join('')}</select></div>`;}
const choose=kind=>[['','Selecione…'],...list(kind).map(a=>[a.id,a.name])];
function openDialog(name,html,submit){$('#dialog-title').textContent=name;$('#dialog-content').innerHTML=html;$('#form-error').textContent='';$('#editor').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=e.submitter;b.disabled=true;try{await submit(new FormData(e.target));modal.close();}catch(err){$('#form-error').textContent=err.message.includes('CONFLICT')?'Este registro mudou em outro dispositivo. Feche, atualize e tente novamente.':err.message;}finally{busy=false;b.disabled=false;}};modal.showModal();}
async function saveOps(ops){await api.save(ops);try{await load();render();toast('Salvo. Os dados já estão disponíveis para a família.');}catch{modal.close();showSyncError();toast('Salvo no servidor, mas não foi possível atualizar a tela. Use Atualizar.');}}
function op(kind,data,id){const old=rows.find(r=>r.id===id);return {id:id||uid(),kind,data,version:old?.version||0};}
function categoryField(type,value=''){
 const standard=standardCategories(type);
 const previous=entries().filter(e=>type==='income'?e.type==='income':isSpending(e)).map(e=>e.category).concat(type==='income'?[]:list('budget').map(b=>b.category));
 const additional=[...new Set([...previous,value].filter(c=>c&&!standard.includes(c)))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 const selected=value||(type==='income'?'Outras receitas':'Outros');
 const options=names=>names.map(c=>`<option value="${esc(c)}" ${c===selected?'selected':''}>${esc(c)}</option>`).join('');
 return `<div class="field" data-field="category"><label for="f-category">Categoria</label><select id="f-category" name="category"><optgroup label="${type==='income'?'Ganhos / receitas':'Gastos / despesas'}">${options(standard)}</optgroup>${additional.length?`<optgroup label="Suas categorias">${options(additional)}</optgroup>`:''}<option value="__new_category__">+ Criar outra categoria…</option></select><div id="custom-category" hidden style="margin-top:12px"><label for="f-custom-category">Nome da nova categoria</label><input id="f-custom-category" name="customCategory" maxlength="100" placeholder="Ex.: Academia" disabled></div></div>`;
}
function bindCategory(){const select=$('#f-category');if(!select)return;select.onchange=()=>{const custom=select.value==='__new_category__';$('#custom-category').hidden=!custom;$('#f-custom-category').disabled=!custom;$('#f-custom-category').required=custom;if(custom)$('#f-custom-category').focus();};}
function edit(kind,id='',defaults={}){
 const d={...(find(kind,id)||{}),...defaults};if(kind==='entry'&&!id&&!d.date&&month>today().slice(0,7)){d.date=month+'-01';if(!d.type||['income','expense'].includes(d.type))d.status='pending';}editor={kind,id};
 if(kind==='entry'&&!list('account').length){toast('Cadastre uma conta antes de registrar lançamentos.');page='accounts';render();return;}
 let html='';
 if(kind==='account')html=field('name','Nome da conta',d.name,'text','',true,'required maxlength="120"')+field('bank','Banco / instituição',d.bank)+field('initial','Saldo inicial (R$)',inputMoney(d.initial||0),'text','Saldo anterior ao primeiro lançamento. Use negativo se necessário.',false,'required inputmode="decimal"');
 if(kind==='card')html=field('name','Nome do cartão',d.name,'text','',true,'required maxlength="120"')+field('limit','Limite total (R$)',inputMoney(d.limit||0),'text','',true,'required inputmode="decimal"')+field('closing','Dia de fechamento',d.closing||25,'number','Compras no dia de fechamento vão para a próxima fatura.',false,'min="1" max="31" required')+field('due','Dia de vencimento',d.due||5,'number','Se for menor ou igual ao fechamento, vence no mês seguinte.',false,'min="1" max="31" required');
 if(kind==='project')html=field('name','Nome do projeto',d.name,'text','',true,'required maxlength="120"')+field('description','Descrição',d.description,'text','',true,'maxlength="300"');
 if(kind==='budget')html=field('name','Nome do orçamento',d.name,'text','',true,'required maxlength="120"')+categoryField('expense',d.category||'Alimentação')+field('target','Limite mensal (R$)',inputMoney(d.target||0),'text','O mesmo limite se aplica a cada mês.',false,'required inputmode="decimal"');
 if(kind==='goal')html=field('name','Nome da meta',d.name,'text','',true,'required maxlength="120"')+field('target','Valor desejado (R$)',inputMoney(d.target||0),'text','',false,'required inputmode="decimal"')+field('saved','Já reservado (R$)',inputMoney(d.saved||0),'text','Não altera o saldo de suas contas.',false,'required inputmode="decimal"')+field('deadline','Prazo (opcional)',d.deadline,'date','',true);
 if(kind==='entry')html=select('type','Tipo',Object.entries(types),d.type||'expense',true)+field('description','Descrição',d.description,'text','',true,'required maxlength="200"')+field('amount','Valor total (R$)',inputMoney(d.amount||0),'text','',false,'required inputmode="decimal"')+field('date','Data do lançamento / vencimento',d.date||today(),'date','Data futura fica pendente automaticamente. Para confirmados: data efetiva.',false,'required')+select('account','Conta',choose('account'),d.account||list('account')[0]?.id)+select('to','Conta de destino',choose('account'),d.to)+select('card','Cartão',choose('card'),d.card||list('card')[0]?.id)+field('bill','Fatura (mês de fechamento)',d.bill||month,'month','Ajuste se a compra entrar em outra fatura.')+categoryField(d.type||'expense',d.category)+select('status','Situação',[['paid','Confirmado'],['pending','Pendente']],d.status||'paid')+select('project','Projeto (opcional)',[['','Sem projeto'],...list('project').map(p=>[p.id,p.name])],d.project)+(!id?field('count','Parcelas / repetições',1,'number','Cartão: divide o total. Receita/despesa: repete o valor mensal e deixa os próximos pendentes.',false,'min="1" max="120" required'):'')+field('note','Observações',d.note,'text','',true,'maxlength="1000"');
 openDialog(`${id?'Editar':'Novo'} ${title(kind)}`,`<div class="formgrid">${html}</div>`,async fd=>{
 let data=Object.fromEntries(fd);
 if(data.category==='__new_category__'){data.category=String(data.customCategory||'').trim();if(!data.category||data.category==='__new_category__')throw Error('Informe o nome da nova categoria.');}
 delete data.customCategory;
 if(kind==='account')data.initial=cents(data.initial);
 if(kind==='card'){data.limit=cents(data.limit);data.closing=Number(data.closing);data.due=Number(data.due);if(data.limit<0)throw Error('Limite inválido.');}
 if(kind==='budget'||kind==='goal'){data.target=cents(data.target);if(data.target<=0)throw Error('Informe um objetivo maior que zero.');}
 if(kind==='goal'){data.saved=cents(data.saved);if(data.saved<0)throw Error('Reserva inválida.');}
 if(kind==='entry'){
 data={...d,...data,amount:cents(data.amount)};delete data.id;delete data.version;
 if(data.type==='card'){data.account='';data.to='';data.status='paid';}
 else if(data.type==='transfer'){data.card='';data.bill='';data.status='paid';data.category='Transferência';}
 else if(data.type==='card_payment'){data.to='';data.status='paid';data.category='Pagamento de fatura';}
 else{data.to='';data.card='';data.bill='';}
 if(['income','expense'].includes(data.type)&&data.date>today())data.status='pending';
 if(data.status==='paid'&&data.type!=='card'&&data.date>today())throw Error('Pagamentos de fatura e transferências só podem ser confirmados até hoje.');
 if(data.type==='card_payment'){const due=cardBill(entries().filter(e=>e.id!==id),data.card,data.bill);if(data.amount>due)throw Error('O pagamento supera o saldo desta fatura.');}
 const n=!id?Number(data.count||1):1;delete data.count;if(!Number.isInteger(n)||n<1||n>120)throw Error('Quantidade inválida.');if(['transfer','card_payment'].includes(data.type)&&n!==1)throw Error('Esta movimentação não pode ser repetida.');
 if(data.type==='card'&&data.amount<n)throw Error('O valor é insuficiente para essa quantidade de parcelas.');
 const amounts=data.type==='card'?split(data.amount,n):Array(n).fill(data.amount),group=n>1?uid():data.group;
 const ops=amounts.map((a,i)=>{let part={...data,amount:a,date:addMonths(data.date,i)};if(group)part.group=group;if(n>1){part.installment=`${i+1}/${n}`;if(data.type==='card')part.bill=addMonths(data.bill+'-01',i).slice(0,7);else if(i>0)part.status='pending';}validate(kind,part);return op(kind,part,id);});
 await saveOps(ops);return;
 }
 validate(kind,data);await saveOps([op(kind,data,id)]);
 });
 bindCategory();
 if(kind==='entry'){const adapt=()=>{const t=$('#f-type').value;['account','to','card','bill','status','category','count'].forEach(name=>{const el=$(`[data-field="${name}"]`);if(!el)return;const hide=name==='account'?t==='card':name==='to'?t!=='transfer':['card','bill'].includes(name)?!['card','card_payment'].includes(t):name==='status'?['card','card_payment','transfer'].includes(t):name==='count'?['transfer','card_payment'].includes(t):['transfer','card_payment'].includes(t);el.hidden=hide;el.querySelector('input,select').disabled=hide;});};$('#f-type').onchange=()=>{const type=$('#f-type').value,current=$('#f-category').value;const keep=standardCategories(type).includes(current)?current:'';$('[data-field="category"]').outerHTML=categoryField(type,keep);bindCategory();adapt();syncFutureStatus();autobill();};const syncFutureStatus=()=>{if(['income','expense'].includes($('#f-type').value)&&$('#f-date').value>today())$('#f-status').value='pending';};const autobill=()=>{if($('#f-type').value!=='card')return;const c=find('card',$('#f-card').value);if(c){const m=billMonth($('#f-date').value,c.closing);$('#f-bill').innerHTML=monthOptions(m);}};$('#f-date').onchange=()=>{syncFutureStatus();autobill();};$('#f-card').onchange=autobill;adapt();syncFutureStatus();if(!id&&d.type==='card')autobill();}
}
function settle(id){const e=find('entry',id);openDialog('Confirmar pagamento / recebimento',`<p>${esc(e.description)} · saldo pendente ${money(e.amount)}</p><div class="formgrid">${field('amount','Valor liquidado (R$)',inputMoney(e.amount),'text','Se parcial, o restante continuará pendente.',true,'required inputmode="decimal"')}${field('date','Data efetiva',today(),'date','',true,`required max="${today()}"`)}</div>`,async fd=>{const paid=cents(fd.get('amount'));if(paid<=0||paid>e.amount)throw Error('Informe um valor entre zero e o saldo pendente.');const d={...e};delete d.id;delete d.version;const settled={...d,amount:paid,date:fd.get('date'),dueDate:e.date,status:'paid'};validate('entry',settled);const ops=paid===e.amount?[op('entry',settled,id)]:[op('entry',{...d,amount:e.amount-paid},id),op('entry',{...settled,description:e.description+' (parcial)',source:id})];await saveOps(ops);});}
async function remove(kind,id){const d=find(kind,id);openDialog('Excluir '+title(kind),`<p>Excluir <strong>${esc(d.name||d.description)}</strong>?</p><p class="muted">${d.group?'Somente esta parcela ou ocorrência será excluída.':'Esta ação altera os relatórios e saldos relacionados.'} Você pode baixar um backup antes de continuar.</p>`,async()=>{await saveOps([{id,kind,version:d.version,delete:true}]);});}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
const csvCols=['id','tipo','descricao','valor_centavos','data','situacao','conta_id','destino_id','cartao_id','fatura','categoria','projeto_id','observacoes'];
function exportCSV(all=false){const es=all?entries():filtered();const quote=v=>{let text=String(v??'');if(/^[=+@\-\t\r]/.test(text)||text.startsWith("'"))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';};const lines=es.map(e=>[e.id,e.type,e.description,e.amount,e.date,e.status,e.account,e.to,e.card,e.bill,e.category,e.project,e.note]);download('lancamentos-'+(all?'todos':month)+'.csv','\uFEFF'+[csvCols,...lines].map(r=>r.map(quote).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
function parseCSV(s){s=s.replace(/^\uFEFF/,'');const out=[];let row=[],v='',quoted=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){v+='"';i++;}else quoted=!quoted;}else if(c===';'&&!quoted){row.push(v);v='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&s[i+1]==='\n')i++;row.push(v);if(row.some(Boolean))out.push(row);row=[];v='';}else v+=c;}if(quoted)throw Error('CSV com aspas incompletas.');row.push(v);if(row.some(Boolean))out.push(row);return out;}
function readFile(accept,callback){const inp=document.createElement('input');inp.type='file';inp.accept=accept;inp.onchange=async()=>{try{const file=inp.files[0];if(!file)return;if(file.size>3000000)throw Error('Use um arquivo de até 3 MB.');await callback(await file.text());}catch(e){toast(e.message);}};inp.click();}
function validateRefs(data,set=rows){for(const [field,kind] of [['account','account'],['to','account'],['card','card'],['project','project']])if(data[field]&&!set.some(r=>r.kind===kind&&r.id===data[field]))throw Error(`Referência inválida: ${field}. Cadastre a conta, cartão ou projeto correspondente.`);}
function importCSV(){readFile('.csv',text=>{const parsed=parseCSV(text),head=parsed.shift();if(head?.join('|')!==csvCols.join('|'))throw Error('Formato diferente do esperado. Exporte um CSV do aplicativo e mantenha o cabeçalho.');const seen=new Set(rows.map(r=>r.id)),ops=[];let ignored=0;for(const raw of parsed){const r=raw.map(v=>/^'[=+@\-\t\r']/.test(v)?v.slice(1):v);if(r.length!==csvCols.length)throw Error('Quantidade de colunas inválida.');const [id,type,description,am,date,status,account,to,card,bill,category,project,note]=r;if(id&&seen.has(id)){ignored++;continue;}if(id&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))throw Error('ID inválido no CSV.');const data={type,description,amount:Number(am),date,status,account,to,card,bill,category,project,note};validate('entry',data);validateRefs(data);const newId=id||uid();seen.add(newId);ops.push({id:newId,kind:'entry',data,version:0});}if(ops.length>1000)throw Error('Importe no máximo 1.000 linhas por vez.');openDialog('Revisar importação',`<p><strong>${ops.length}</strong> lançamentos serão adicionados.</p><p>${ignored} linhas ignoradas por ID já existente.</p><p class="muted">Linhas sem ID recebem um novo identificador. Importar o mesmo arquivo sem IDs novamente cria duplicatas.</p>${entryTable(ops.slice(0,5).map(o=>({...o.data,id:o.id})),true)}`,async()=>{if(ops.length)await saveOps(ops);});});}
function restore(){readFile('.json',text=>{const backup=JSON.parse(text);if(backup.format!=='meu-financeiro-v1'||!Array.isArray(backup.records))throw Error('Backup incompatível.');if(backup.records.length+rows.length>1000)throw Error('Restauração pela interface limitada a 1.000 operações. Consulte o guia.');const ids=new Set();for(const r of backup.records){if(!['account','entry','card','budget','goal','project'].includes(r.kind)||!r.id||ids.has(r.id))throw Error('Registro inválido ou duplicado.');ids.add(r.id);validate(r.kind,r.data);}backup.records.filter(r=>r.kind==='entry').forEach(r=>validateRefs(r.data,backup.records));const ops=[...rows.filter(r=>!ids.has(r.id)).map(r=>({id:r.id,kind:r.kind,version:r.version,delete:true})),...backup.records.map(r=>({id:r.id,kind:r.kind,data:r.data,version:rows.find(x=>x.id===r.id)?.version||0}))];openDialog('Restaurar backup',`<p>O backup tem <strong>${backup.records.length} registros</strong>.</p><p class="error">Os dados atuais dos dois usuários serão substituídos pelos dados deste arquivo.</p>${field('confirm','Digite RESTAURAR para confirmar','','text','Faça um backup atual antes de prosseguir.',true,'required')}`,async fd=>{if(fd.get('confirm')!=='RESTAURAR')throw Error('Digite RESTAURAR para confirmar.');await saveOps(ops);});});}
root.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||busy)return;const a=el.dataset.action;try{
 if(a==='page'){page=el.dataset.page;render();window.scrollTo({top:0,behavior:'instant'});}
 if(a==='more')$('#nav-dialog').showModal();
 if(a==='close-more')$('#nav-dialog').close();
 if(a==='previous-month'||a==='next-month'){month=addMonths(month+'-01',a==='previous-month'?-1:1).slice(0,7);render();}
 if(a==='new')edit(el.dataset.kind);
 if(a==='edit')edit(el.dataset.kind,el.dataset.id);
 if(a==='delete')remove(el.dataset.kind,el.dataset.id);
 if(a==='settle')settle(el.dataset.id);
 if(a==='purchase')edit('entry','',{type:'card',card:el.dataset.id});
 if(a==='pay-card'){const c=find('card',el.dataset.id),bill=el.dataset.bill||month;edit('entry','',{type:'card_payment',date:today(),card:c.id,bill,amount:cardBill(entries(),c.id,bill),description:'Fatura '+c.name+' · '+periodText(bill)});}
 if(a==='refresh'){el.disabled=true;await load();render();toast('Dados atualizados.');}
 if(a==='logout'){try{await api.logout();}finally{login();}}
 if(a==='privacy'){hidden=!hidden;render();}
 if(a==='theme'){document.body.classList.toggle('dark');localStorage.setItem('mf-theme',document.body.classList.contains('dark')?'dark':'light');render();}
 if(a==='password')openDialog('Alterar minha senha',field('password','Nova senha','','password','Use uma senha única de pelo menos 12 caracteres.',true,'required minlength="12" autocomplete="new-password"')+field('confirmation','Repita a nova senha','','password','',true,'required minlength="12" autocomplete="new-password"'),async fd=>{if(fd.get('password')!==fd.get('confirmation'))throw Error('As senhas não conferem.');await api.password(fd.get('password'));toast('Senha alterada.');});
 if(a==='backup')download('meu-financeiro-backup-'+today()+'.json',JSON.stringify({format:'meu-financeiro-v1',exportedAt:new Date().toISOString(),records:rows.map(({id,kind,data})=>({id,kind,data}))},null,2),'application/json');
 if(a==='restore')restore();if(a==='csv')exportCSV();if(a==='csv-all')exportCSV(true);if(a==='import')importCSV();if(a==='print')window.print();
 }catch(err){toast(err.message);if(a==='refresh'){el.disabled=false;showSyncError();}}});
root.addEventListener('change',e=>{if(e.target.id==='period'){month=e.target.value||today().slice(0,7);render();}if(e.target.id==='type-filter'){typeFilter=e.target.value;$('#entries-table').innerHTML=entryTable(filtered());}if(e.target.id==='status-filter'){statusFilter=e.target.value;$('#entries-table').innerHTML=entryTable(filtered());}if(e.target.id==='account-filter'){accountFilter=e.target.value;$('#entries-table').innerHTML=entryTable(filtered());}});
root.addEventListener('input',e=>{if(e.target.id==='search'){filter=e.target.value;$('#entries-table').innerHTML=entryTable(filtered());}});
modal.addEventListener('click',e=>{if(e.target.closest('[data-close]')&&!busy)modal.close();});modal.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
window.addEventListener('session-expired',()=>login('Sua sessão expirou. Entre novamente.'));
try{if(localStorage.getItem('mf-theme')==='dark')document.body.classList.add('dark');}catch{}
const recovery=configured()&&api.recoverFromURL();
if(configured()&&api.user){start().then(()=>{if(recovery&&member)root.querySelector('[data-page="settings"]').click();if(recovery&&member)root.querySelector('[data-action="password"]').click();});}else login();
